[package]
name = "dealer"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossbeam-utils = "0.8"
crossbeam-channel = "0.5"
rustc-hash = "1.1"

[[bin]]
name = "deal"
path = "src/main.rs"
