// Auto-generated by deal codegen
#![allow(unused_variables)]
#![allow(unused_mut)]

fn print<T: std::fmt::Display>(x: T) { println!("{}", x); }

fn main() {
    let nums = vec![1, 2, 3, 4];
    for n in nums.iter() {
        print(n);
    }
    let words = vec!["ace".to_string(), "king".to_string(), "queen".to_string()];
    for w in words.iter() {
        print(w);
    }
    let empty_ints = Vec::<i64>::new();
    for x in empty_ints.iter() {
        print(x);
    }
    for (i, v) in nums.iter().enumerate() {
        print(i);
        print(v);
    }
}
